swagger: '2.0'
info:
  title: Cloud Endpoints Event API Example
  description: Cloud Endpoints Event API Example
  version: "0.0.1"

x-global-options:
  go_package: "proto/event;event"

tags:
  - name: CloudEndpoints

produces:
  - application/json
consumes:
  - application/json

host: 0.0.0.0
schemes:
  - https

basePath: /api

paths:
  /{ServiceName}/event/{EventType}:
    post:
      tags:
        - Event API
      summary: Event API
      description: |-
        Event API for Saving Events
      parameters:
        - name: ServiceName
          in: path
          description: |-
            Service Name for the routing of the Event
          required: true
          minLength: 1
          pattern: \S+
          type: string
        - name: EventType
          in: path
          description: |-
            Event Type Based on Configured Types
          required: true
          minLength: 1
          pattern: \S+
          type: string
        - name: Event
          description: Event Payload
          in: body
          schema:
            $ref: '#/definitions/EventData'
          required: true
      responses:
        "200":
          description: Event Body Response
          schema:
            $ref: '#/definitions/EventSuccessResponse'


  /{ServiceName}/event/{EventType/{EventId}:
    get:
      tags:
        - Event API
      summary: Event API
      description: |-
        Event API
      parameters:
        - name: ServiceName
          in: path
          description: |-
            Service Name for the routing of the Event
          required: true
          minLength: 1
          pattern: \S+
          type: string
        - name: EventType
          in: path
          description: Event Type
          required: true
          minLength: 1
          pattern: \S+
          type: string
        - name: EventId
          in: path
          description: Unique EventId
          required: true
          minLength: 1
          pattern: \S+
          type: string
      responses:
        "200":
          description: Event Payload
          schema:
            $ref: '#/definitions/Event'


definitions:

  NonEmptyString:
    minLength: 1
    pattern: \S+
    type: string

  DateTime:
    $ref: "google/protobuf/timestamp.proto#/google.protobuf.Timestamp"
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z$'
    description: DateTime in ISO 8601 format, UTC e.g. 2018-08-30T15:39:42.025Z
    format: date-time
    example: '2020-12-20T12:12:12.000Z'

  EventSuccessResponse:
    type: object
    properties:
      id:
        type: string

  EventHeader:
    type: object
    description: Event Header Attributes Sent Back in the Event Get Request Response
    properties:
      eventType:
        type: string
      eventSource:
        type: string
      eventId:
        type: string
      eventTimestamp:
        $ref: '#/definitions/DateTime'
      eventSchema:
        type: string
      eventModel:
        type: string


  EventData:
    description: |-
      Event Data of the Any Proto Type that allows the Payload to be Decoded to the exact Proto Type
      The Proto Type must be defined within the Proto / API Spec to be successfully decoded
    type: object
    properties:
      data:
        $ref: "google/protobuf/any.proto#/google.protobuf.Any"

  Event:
    type: object
    description: Event Header and Data Attributes Sent Back in the Event Get Request Response
    properties:
      eventType:
        type: string
      eventSource:
        type: string
      eventId:
        type: string
      eventTimestamp:
        $ref: '#/definitions/DateTime'
      eventSchema:
        type: string
      eventModel:
        type: string
      data:
        $ref: "google/protobuf/any.proto#/google.protobuf.Any"

  ExampleEventAnyModel:
    type: object
    description: Example Event Model that Can Be used within Event Data to be passed to backend services
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      raw:
        type: string

